set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(BUILDROOT_ROOT /home/ciyeer/source/rk356x_linux/buildroot)
set(BUILDROOT_HOST ${BUILDROOT_ROOT}/output/host)
set(BUILDROOT_SYSROOT ${BUILDROOT_HOST}/aarch64-buildroot-linux-gnu/sysroot)

set(CMAKE_C_COMPILER ${BUILDROOT_HOST}/bin/aarch64-buildroot-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${BUILDROOT_HOST}/bin/aarch64-buildroot-linux-gnu-g++)
set(CMAKE_SYSROOT ${BUILDROOT_SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${BUILDROOT_SYSROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
